### ISSUE TITLE
Accessibility improvements

### ISSUE THREAD

**Issue by oliverjam** [bobbysebolao/learn-layout-spacing#3]
There are a few tweaks that would improve the accessibility of the solution:

1. Use links instead of buttons for the "Read post" element.
    - Presumably this would link to the full blog post on a real site, rather than toggle some JS functionality
1. Use more descriptive link text for "Read post" elements
    - Currently if a screen reader user gets a list of all links (or tabs through the list) they'll just hear "Read post" over and over with no context
    - If you think it's clear which link applies to which post for visual users then you could add hidden text/an `aria-label` with "Read {post title}" for screen reader users
1. The date text is too low contrast (~3.2 right now). It needs to be quite a bit darker to be properly visible

**Comment by bobbysebolao** [comment]
Thanks for this feedback @oliverjam , I'm pushing a commit that should address all of these things that you've pointed out!
